spring:
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog.xml
    enabled: true
    drop-first: false
    default-schema: public
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.23.109.251:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    database: POSTGRESQL
    show-sql: true


